### ISSUE TITLE
todo list 기능 완성

### ISSUE THREAD

**Issue by debugbunnys** [ayyb/todo-vue#1]
## 목적
> todo에 맞는 기능사항 추가

## 작업상세내용
- [x] css 변경 - 간단한 ui/ux
- [x] 리스트 입력 날짜 표시
- [x] 체크박스 클릭시 완료 여부 확인 가능하게 line처리(css)
- [x] 타이틀에  남은목록/전체목록 카운트 표시 :computed
- [x] 수정 버튼 추가 후 클릭 시 수정 가능하게
- [x] clearAll 기능 추가
- [x] ordering 기능 추가
- [x] 사용자 이름 입력페이지 간단한 css
- [x] 모달창 추가해보기

**Comment by debugbunnys** [comment]
전체적 기능 추가 완료
